/**
 * The software layer, shown as it actually is — hand-written firmware plus the
 * two web files that talk to it.
 */

export type CodeFile = {
  id: string;
  name: string;
  lang: string;
  blurb: string;
  meta: string;
  lines: string[];
};

export const CODE_FILES: CodeFile[] = [
  {
    id: "core",
    name: "verde_core.cpp",
    lang: "cpp",
    blurb:
      "The control loop. Non-blocking by construction — every sensor is polled on its own schedule, and nothing in the path of a watering decision is allowed to wait on the network.",
    meta: "438 lines · ESP32 / ESP8266 dual target",
    lines: [
      "// ============================================================",
      "// PROJECT VERDE - AUTONOMOUS PLANT OS",
      "// lead: Anuj Phulera   hardware: Aarav Choudhary",
      "// target: ESP32-WROOM-32 / ESP8266 (dual build)",
      "// ============================================================",
      "",
      "#include <Arduino.h>",
      "#include \"plant_profile.h\"",
      "#include \"telemetry.h\"",
      "",
      "static constexpr uint32_t POLL_INTERVAL_MS   = 90000;",
      "static constexpr uint32_t MIN_COOLDOWN_MS    = 4UL * 60UL * 60UL * 1000UL;",
      "static constexpr float    TANK_FLOOR_PCT     = 15.0f;",
      "",
      "static PlantProfile profile;      // active specimen",
      "static uint32_t lastIrrigation = 0;",
      "static bool     tankDry        = false;",
      "",
      "// -- sensors are read, never trusted blindly -----------------------",
      "float readSoilMoisture(uint8_t samples = 8) {",
      "  uint32_t acc = 0;",
      "  for (uint8_t i = 0; i < samples; i++) {",
      "    acc += analogRead(PIN_SOIL);",
      "    delay(4);",
      "  }",
      "  float raw = acc / (float)samples;",
      "  return calibrate(raw, profile.dryCount, profile.wetCount);",
      "}",
      "",
      "// -- the decision: fuzzy band, cooldown, tank, then act ------------",
      "void evaluateIrrigation() {",
      "  const float moisture = readSoilMoisture();",
      "  const uint32_t since = millis() - lastIrrigation;",
      "",
      "  if (moisture >= profile.moistureTarget) return;",
      "  if (since < MIN_COOLDOWN_MS)          return;",
      "  if (tankDry) { alert(ALERT_TANK_DRY); return; }",
      "",
      "  LOG(\"[LOG] TRIGGER_PUMP moisture=%.1f target=%.1f\",",
      "      moisture, profile.moistureTarget);",
      "",
      "  relayOn(RELAY_K1);                    // zero-cross switch",
      "  delay(profile.burstDurationMs);        // 4-11 s per specimen",
      "  relayOff(RELAY_K1);",
      "  lastIrrigation = millis();",
      "",
      "  telemetryPush(\"irrigation\", moisture);",
      "}",
      "",
      "// -- the cloud is observability, never the control path ------------",
      "void checkForecast() {",
      "  Forecast f = weather.fetchTomorrow();",
      "  if (!f.valid) return;                  // offline: keep growing",
      "  if (f.tempMax > 38.0f && !f.rainLikely) {",
      "    schedulePreIrrigation(TONIGHT_22_00, 1.18f);",
      "    LOG(\"[AI] pre-irrigate scheduled, +18%% volume\");",
      "  }",
      "}",
      "",
      "// -- the human channel ---------------------------------------------",
      "void onWhatsApp(const String &msg) {",
      "  if (msg == \"paani do\" || msg == \"water now\") {",
      "    manualOverride(PUMP_ON, /*autoReturn*/ 30UL * 60UL * 1000UL);",
      "  } else if (msg == \"status\") {",
      "    sendStatusReport();                  // moisture, tank, uv, last",
      "  } else {",
      "    sendStatusReport();                  // unknown intent: be useful",
      "  }",
      "}",
      "",
      "void setup() {",
      "  prefs.begin(\"verde\");",
      "  profile = loadProfile(prefs.getString(\"active\", \"tulsi\"));",
      "  net.begin();                           // does not block boot",
      "  aio.begin(profile);                    // grow state machine",
      "  watchdog.enable(30);                   // relay rail fails safe",
      "}",
      "",
      "void loop() {",
      "  scheduler.tick();                      // polls every sensor, non-blocking",
      "  evaluateIrrigation();",
      "  checkForecast();",
      "  vision.maybeScan(profile);             // 6-hourly, pump rail idle",
      "  telemetry.flushIfConnected();          // buffered when offline",
      "  watchdog.kick();",
      "  delay(10);",
      "}",
    ],
  },
  {
    id: "api",
    name: "route.ts",
    lang: "ts",
    blurb:
      "The read path. The dashboard never talks to Firebase directly — it asks this route, which normalises the payload and refuses to serve a stale reading as if it were live.",
    meta: "Next.js route handler · edge runtime",
    lines: [
      "import { NextResponse } from \"next/server\";",
      "import { snapshotForPods } from \"@/lib/telemetry\";",
      "",
      "export const runtime = \"edge\";",
      "export const revalidate = 0;",
      "",
      "export async function GET(request: Request) {",
      "  const url = new URL(request.url);",
      "  const pods = (url.searchParams.get(\"pods\") ?? \"tulsi,tomato,mint\")",
      "    .split(\",\")",
      "    .map((p) => p.trim())",
      "    .filter(Boolean)",
      "    .slice(0, 4);",
      "",
      "  const snapshot = snapshotForPods(pods, new Date());",
      "",
      "  return NextResponse.json(snapshot, {",
      "    headers: {",
      "      \"cache-control\": \"no-store, max-age=0\",",
      "      \"x-verde-source\": snapshot.source,   // \"simulated\" until creds land",
      "    },",
      "  });",
      "}",
    ],
  },
  {
    id: "card",
    name: "VitalTile.tsx",
    lang: "tsx",
    blurb:
      "One tile from the telemetry grid. Reads from the same schema the pods write, so pointing it at a live Firebase subtree changes nothing above this line.",
    meta: "React 19 · client component",
    lines: [
      "\"use client\";",
      "",
      "import { Sparkline } from \"@/components/ui/Sparkline\";",
      "import { cn } from \"@/lib/utils\";",
      "",
      "type Vital = {",
      "  key: string;",
      "  label: string;",
      "  value: number;",
      "  unit: string;",
      "  band: [number, number];",
      "  trend: number[];",
      "  stale?: boolean;",
      "};",
      "",
      "export function VitalTile({ vital }: { vital: Vital }) {",
      "  const [floor, ceiling] = vital.band;",
      "  const state =",
      "    vital.value < floor ? \"deficit\"",
      "    : vital.value > ceiling ? \"excess\"",
      "    : \"nominal\";",
      "",
      "  return (",
      "    <article className={cn(\"panel p-5\", vital.stale && \"opacity-60\")}>",
      "      <header className=\"label\">{vital.label}</header>",
      "      <p className=\"num text-3xl text-bone\">",
      "        {vital.value.toFixed(1)}",
      "        <span className=\"text-sage text-sm\">{vital.unit}</span>",
      "      </p>",
      "      <Sparkline data={vital.trend} band={vital.band} />",
      "      <footer className=\"label\">{state}</footer>",
      "    </article>",
      "  );",
      "}",
    ],
  },
];

export const BOOT_SEQUENCE: { text: string; ms: number }[] = [
  { text: "verde bios v4.0.0 — 240 MHz dual core", ms: 120 },
  { text: "mounting flash preferences ......... ok", ms: 150 },
  { text: "loading plant profiles ............ 12 found", ms: 130 },
  { text: "calibrating soil probe (8 samples)  ok", ms: 180 },
  { text: "rs485 bus · npk probe ............ 9600 baud", ms: 120 },
  { text: "ov2640 sensor · 2 mp ............. detected", ms: 140 },
  { text: "tflite int8 model ................ 14 classes", ms: 170 },
  { text: "firebase handshake ............... 25 ms rtt", ms: 160 },
  { text: "weather api · 48 h horizon ....... cached", ms: 120 },
  { text: "watchdog armed on relay rail ..... 30 s", ms: 130 },
  { text: "8 nodes nominal · state READY", ms: 200 },
];

export const RUNTIME_LOG: string[] = [
  "SENS  moisture=71.2% target=72% temp=24.2C",
  "CLOUD PATCH /pods/tulsi/telemetry → 25 ms",
  "ACT   relay K1 energised, burst 8000 ms",
  "AI    fuzzy deficit confirmed, cooldown ok",
  "NPK   N=45 P=23 K=67 · within profile band",
  "TANK  level 78% · floor 15% · nominal",
  "UV    array ON · 380-780 nm · 68% duty",
  "RAIN  plate dry · schedules armed",
  "ML    frame 0914 → healthy 96.4% conf",
  "WHATSAPP inbound: “paani do” → pump on",
  "CAM   capture skipped · pump rail busy",
  "SYNC  offline queue empty",
  "AI    pre-irrigation booked 22:00 (+18%)",
  "PWR   buck 5.02 V · rail stable under load",
  "NET   rssi −42 dBm · 2.4 GHz ch 6",
  "WDT   kick · loop jitter 3 ms",
];
